const menu=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');menu?.addEventListener('click',()=>links.classList.toggle('open'));
if(!document.querySelector('link[rel="icon"]')){const icon=document.createElement('link');icon.rel='icon';icon.href='favicon.svg';document.head.appendChild(icon)}if(!document.querySelector('link[rel="manifest"]')){const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='site.webmanifest';document.head.appendChild(manifest)}
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('form[data-mailto]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;const email=form.querySelector('[type="email"]')?.value.trim()||'';const name=form.querySelector('[name="name"]')?.value.trim()||'';const message=form.querySelector('[name="message"]')?.value.trim()||'';const recipient=form.dataset.mailto||'support@gunnarschuster.com';const subject=form.dataset.subject||'Anfrage über gunnarschuster.com';const body=[name&&`Name: ${name}`,email&&`E-Mail: ${email}`,message&&`Nachricht:\n${message}`].filter(Boolean).join('\n\n');window.location.href=`mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;}));
const searchPages=[['Startseite','Krypto verstehen, Kurse, Videos und Tools','index.html'],['Ratgeber','Bitcoin kaufen, Steuern, Wallets und Grundlagen','ratgeber.html'],['Videos','Analysen, Bitcoin, Sicherheit und Marktpsychologie','videos.html'],['Tools','Rechner, Coin Check, Portfolio und Steuern','tools.html'],['Kurse','Krypto Freiheit, Krypto Multiplikator und KI Analyst','kurse.html'],['Krypto Freiheit','Premium-Kurs, Strategie und Exit-Plan','krypto-freiheit.html'],['Krypto Multiplikator','8 Module, Marktzyklen, Tokenomics und DeFi','krypto-multiplikator.html'],['KI Krypto-Analyst','Coin-Recherche mit KI und Checklisten','ki-krypto-analyst.html'],['Bitcoin kaufen','Sicherer Einstieg für Anfänger','bitcoin-kaufen.html'],['Krypto-Steuern','Haltefrist, Tausch und Dokumentation','krypto-steuern.html'],['Wallet-Sicherheit','Self-Custody, Seed Phrase und Schutz','wallet-sicherheit.html'],['Coin Check','Projekt und Altcoin analysieren','coin-check.html'],['Bitcoin Sparplan','Sparplan berechnen','bitcoin-sparplan-rechner.html'],['Portfolio Tracker','Positionen und Allokation verwalten','portfolio-tracker.html'],['Über mich','Gunnars Geschichte, Methode und Transparenz','ueber.html'],['Kontakt','Fragen zu Kursen, Presse und Support','kontakt.html']];
const searchStyle=document.createElement('style');searchStyle.textContent='.search-overlay{position:fixed;inset:0;z-index:100;background:rgba(20,19,16,.62);display:grid;place-items:start center;padding:110px 20px}.search-overlay[hidden]{display:none}.search-dialog{width:min(680px,100%);max-height:75vh;overflow:auto;background:var(--paper);border:1px solid var(--line);border-radius:24px;padding:22px;box-shadow:0 30px 80px rgba(0,0,0,.28)}.search-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.search-close{border:0;background:transparent;font-size:30px;cursor:pointer}.search-input{width:100%;padding:16px 18px;border:1px solid var(--line);border-radius:999px;background:#fff;font:inherit}.search-results{display:grid;gap:8px;margin-top:14px}.search-results a{display:flex;justify-content:space-between;gap:18px;padding:14px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.55)}.search-results span{color:var(--muted);font-size:13px;text-align:right}@media(max-width:620px){.search-overlay{padding-top:82px}.search-results a{display:block}.search-results span{display:block;text-align:left}}';document.head.appendChild(searchStyle);
document.querySelectorAll('.nav-actions').forEach(actions=>{if(!actions.querySelector('[aria-label="Suche"]')){const button=document.createElement('button');button.className='icon-btn';button.type='button';button.setAttribute('aria-label','Suche');button.textContent='⌕';actions.insertBefore(button,actions.firstChild)}});
const searchButton=document.querySelector('.icon-btn[aria-label="Suche"]');
if(searchButton){const overlay=document.createElement('div');overlay.className='search-overlay';overlay.hidden=true;overlay.innerHTML='<div class="search-dialog" role="dialog" aria-modal="true" aria-label="Website durchsuchen"><div class="search-head"><strong>Website durchsuchen</strong><button type="button" class="search-close" aria-label="Suche schließen">×</button></div><input class="search-input" type="search" placeholder="Bitcoin, Steuern, Kurs …" aria-label="Suchbegriff"><div class="search-results"></div></div>';document.body.appendChild(overlay);const input=overlay.querySelector('.search-input'),results=overlay.querySelector('.search-results');const render=value=>{const q=value.trim().toLocaleLowerCase('de');const matches=(q?searchPages.filter(page=>(page[0]+' '+page[1]).toLocaleLowerCase('de').includes(q)):searchPages.slice(0,6));results.innerHTML=matches.length?matches.map(page=>`<a href="${page[2]}"><strong>${page[0]}</strong><span>${page[1]}</span></a>`).join(''):'<p>Keine passenden Inhalte gefunden.</p>'};const close=()=>{overlay.hidden=true;document.body.style.overflow=''};searchButton.onclick=()=>{overlay.hidden=false;document.body.style.overflow='hidden';render('');setTimeout(()=>input.focus(),0)};overlay.querySelector('.search-close').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});input.addEventListener('input',()=>render(input.value));}
// Keep the content hub visible across the static prototype without duplicating every header.
document.querySelectorAll('.nav-links').forEach(nav=>{if(!nav.querySelector('[href="ratgeber.html"]')){const link=document.createElement('a');link.href='ratgeber.html';link.textContent='Ratgeber';nav.insertBefore(link,nav.children[1]||null)}});
if(document.querySelector('.hero')&&!document.querySelector('.home-trust')){
  const anchor=[...document.querySelectorAll('.section')].find(s=>s.textContent.includes('Dein Ausgangspunkt'));
  const section=document.createElement('section');section.className='section tight home-trust';section.innerHTML='<div class="shell"><div class="trust-grid"><div class="trust-panel reveal visible"><span class="eyebrow">Warum mir vertrauen?</span><h3>Vertrau mir nicht blind.</h3><p>Prüfe meine öffentlichen Analysen, Quellen, Interessen und Fehler. Gute Finanzbildung zeigt nicht nur Ergebnisse, sondern auch Unsicherheit und Grenzen.</p><a class="btn light" href="ueber.html">Meine Geschichte & Methode →</a></div><div class="evidence-list"><div class="evidence"><strong>Öffentlich nachvollziehbar seit 2020</strong><span>Hunderte frei zugängliche Videos statt anonymer Signale.</span></div><div class="evidence"><strong>Bildung ist mein Geschäftsmodell</strong><span>Keine bezahlten Coin-Empfehlungen; Kooperationen kennzeichne ich transparent.</span></div><div class="evidence"><strong>Quellen statt bloßer Behauptungen</strong><span>Meine Ratgeber nennen Autor, Prüfdatum, Risiken und weiterführende Originalquellen.</span></div></div></div></div>';
  anchor?.parentNode.insertBefore(section,anchor);
  const newsletter=[...document.querySelectorAll('.section')].find(s=>s.querySelector('.newsletter'));
  const content=document.createElement('section');content.className='section';content.innerHTML='<div class="shell"><div class="split-heading"><div><span class="eyebrow">Neu im Ratgeber</span><h2 class="headline">Antworten, die du auch morgen noch brauchst.</h2></div><p>Quellenbasierte Leitfäden für die wichtigsten Entscheidungen deutscher Krypto-Anleger.</p></div><div class="card-grid"><a class="card dark" href="bitcoin-kaufen.html"><div class="meta"><span>Einsteiger</span><span>12 Min.</span></div><h3>Bitcoin sicher kaufen</h3><p>Anbieter, Kosten, Wallet und erster Testkauf.</p><span class="text-link">Leitfaden lesen →</span></a><a class="card" href="krypto-steuern.html"><div class="meta"><span>Deutschland 2026</span><span>15 Min.</span></div><h3>Krypto-Steuern</h3><p>Haltefrist, Tausch und Dokumentation verständlich erklärt.</p><span class="text-link">Leitfaden lesen →</span></a><a class="card" href="wallet-sicherheit.html"><div class="meta"><span>Sicherheit</span><span>10 Min.</span></div><h3>Wallet oder Börse?</h3><p>Verwahrungsrisiken und eine belastbare Sicherheitsroutine.</p><span class="text-link">Leitfaden lesen →</span></a></div><p style="margin-top:24px"><a class="btn ghost" href="ratgeber.html">Alle Ratgeber ansehen →</a></p></div>';
  newsletter?.parentNode.insertBefore(content,newsletter);
}
const filterButtons=document.querySelectorAll('[data-filter]');const libraryItems=document.querySelectorAll('[data-category]');filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(b=>b.classList.remove('active'));button.classList.add('active');const value=button.dataset.filter;libraryItems.forEach(item=>item.hidden=value!=='all'&&!item.dataset.category.split(' ').includes(value))}));
if(location.pathname.endsWith('/tools.html')||location.pathname.endsWith('tools.html')){const toolRoutes={'altcoins-analysieren':'coin-check.html','krypto-portfolio-tracker':'portfolio-tracker.html','bitcoin-sparplan-rechner':'bitcoin-sparplan-rechner.html','krypto-steuer-tool':'krypto-steuer-rechner.html'};document.querySelectorAll('a[href]').forEach(a=>{for(const [key,value] of Object.entries(toolRoutes))if(a.href.includes(key))a.href=value})}
// Persistent DE/EN control. Translation is loaded only after the visitor requests English.
const navActions=document.querySelector('.nav-actions');
if(navActions&&!document.querySelector('.lang-switch')){
  const languageStyle=document.createElement('style');languageStyle.textContent='.lang-switch{display:flex;align-items:center;padding:3px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.45)}.lang-switch button{border:0;background:transparent;color:var(--muted);border-radius:999px;padding:6px 8px;font:600 10px var(--sans);cursor:pointer}.lang-switch button.active{background:var(--ink);color:#fff}.goog-te-banner-frame,.skiptranslate iframe{display:none!important}body{top:0!important}@media(max-width:620px){.lang-switch{margin-left:auto}}';document.head.appendChild(languageStyle);
  const language=document.createElement('div');language.className='lang-switch';language.setAttribute('aria-label','Sprache / Language');language.innerHTML='<button type="button" data-lang="de">DE</button><button type="button" data-lang="en">EN</button><span id="google_translate_element" hidden></span>';
  navActions.insertBefore(language,navActions.firstChild);
  const translated=document.cookie.includes('googtrans=/de/en');language.querySelector(`[data-lang="${translated?'en':'de'}"]`).classList.add('active');
  const loadTranslator=()=>{if(document.querySelector('script[data-translator]'))return;window.googleTranslateElementInit=()=>{new google.translate.TranslateElement({pageLanguage:'de',includedLanguages:'de,en',autoDisplay:false},'google_translate_element');setTimeout(()=>{const select=document.querySelector('.goog-te-combo');if(select){select.value='en';select.dispatchEvent(new Event('change'))}},500)};const script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;script.dataset.translator='true';document.head.appendChild(script)};
  language.querySelector('[data-lang="en"]').onclick=()=>{document.cookie='googtrans=/de/en;path=/;SameSite=Lax';language.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.lang==='en'));loadTranslator()};
  language.querySelector('[data-lang="de"]').onclick=()=>{document.cookie='googtrans=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';location.reload()};
  if(translated)loadTranslator();
}
