const euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const number=new Intl.NumberFormat('de-DE',{maximumFractionDigits:8});
const el=id=>document.getElementById(id);
const money=n=>euro.format(Number.isFinite(+n)?+n:0);
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const memory={};
const storage={get(k,f='[]'){try{return localStorage.getItem(k)||f}catch{return memory[k]||f}},set(k,v){try{localStorage.setItem(k,v)}catch{memory[k]=v}}};
function csvDownload(name,rows){const text=rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';return lines.slice(1).map(line=>line.split(sep).map(v=>v.trim().replace(/^"|"$/g,'').replaceAll('""','"')))}
async function coingecko(path){const response=await fetch(`https://api.coingecko.com/api/v3${path}`,{headers:{accept:'application/json'}});if(!response.ok)throw Error(`Marktdaten: HTTP ${response.status}`);return response.json()}
const coinIds={BTC:'bitcoin',ETH:'ethereum',SOL:'solana',XRP:'ripple',ADA:'cardano',DOGE:'dogecoin',LINK:'chainlink'};

function initSavings(){
  const panel=el('monthly').closest('.tool-panel');
  panel.insertAdjacentHTML('beforeend','<hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><h3>Historischen Sparplan testen</h3><div class="input-pair"><div><label>Startdatum</label><input id="dcaStart" type="date" value="2021-01-01"></div><div><label>Intervall</label><select id="dcaInterval"><option value="30">monatlich</option><option value="7">wöchentlich</option></select></div></div><button class="btn ghost" id="runHistory" style="margin-top:14px">Historische BTC-Daten laden</button><p class="tool-note" id="historyStatus">Datenquelle: CoinGecko. Verfügbarkeit und Zeitraum können durch API-Limits eingeschränkt sein.</p>');
  const project=()=>{const monthly=+el('monthly').value||0,years=+el('years').value||0,annual=+el('return').value/100,rate=Math.pow(1+annual,1/12)-1;let value=0;for(let i=0;i<years*12;i++)value=(value+monthly)*(1+rate);const paid=monthly*years*12;el('future').textContent=money(value);el('paid').textContent=money(paid);el('growth').textContent=money(value-paid);el('assumption').textContent=`${(annual*100).toFixed(1)} %`;el('growthbar').style.width=`${clamp(value?paid/value*100:0,0,100)}%`};
  document.querySelectorAll('#tool input,#tool select').forEach(input=>input.addEventListener('input',project));project();
  el('runHistory').onclick=async()=>{const start=new Date(el('dcaStart').value),end=new Date(),days=+el('dcaInterval').value,budget=+el('monthly').value*(days===7?12/52:1);if(!start.getTime()||start>=end)return;el('historyStatus').textContent='Historische Daten werden geladen …';try{const data=await coingecko(`/coins/bitcoin/market_chart/range?vs_currency=eur&from=${Math.floor(start/1000)}&to=${Math.floor(end/1000)}`);const prices=data.prices||[];if(!prices.length)throw Error('Keine Preisdaten');let cursor=start.getTime(),btc=0,paid=0,purchases=0;while(cursor<=end.getTime()){const point=prices.reduce((best,p)=>Math.abs(p[0]-cursor)<Math.abs(best[0]-cursor)?p:best,prices[0]);btc+=budget/point[1];paid+=budget;purchases++;cursor+=days*86400000}const current=prices.at(-1)[1],value=btc*current;el('future').textContent=money(value);el('paid').textContent=money(paid);el('growth').textContent=money(value-paid);el('assumption').textContent=`${purchases} Käufe`;el('historyStatus').textContent=`Historisch simuliert bis ${new Date(prices.at(-1)[0]).toLocaleDateString('de-DE')}; ${number.format(btc)} BTC zum letzten Datensatz.`}catch(error){el('historyStatus').textContent=`Historische Daten nicht verfügbar (${error.message}). Die Szenario-Berechnung oben funktioniert weiterhin.`}};
}

function initRetirement(){
  const calculate=()=>{const current=+el('current').value||0,monthly=+el('monthly').value||0,years=+el('years').value||0,annual=+el('return').value/100,withdraw=+el('withdraw').value/100,rate=Math.pow(1+annual,1/12)-1;let value=current;for(let i=0;i<years*12;i++)value=(value+monthly)*(1+rate);el('capital').textContent=money(value);el('monthlyIncome').textContent=money(value*withdraw/12);el('totalPaid').textContent=money(current+monthly*years*12);el('realValue').textContent=money(value/Math.pow(1.02,years))};
  document.querySelectorAll('#tool input').forEach(input=>input.addEventListener('input',calculate));calculate();
}

function initPortfolio(){
  const button=el('addHolding');button.insertAdjacentHTML('beforebegin','<div class="input-pair"><div><label>Anschaffungskosten gesamt</label><input id="holdingCost" type="number" value="0"></div><div><label>Kaufdatum</label><input id="holdingDate" type="date"></div></div>');
  let holdings=JSON.parse(storage.get('gs-holdings'));
  const save=()=>storage.set('gs-holdings',JSON.stringify(holdings));
  const render=async()=>{let prices={},total=0,cost=0;el('holdings').innerHTML='';try{const ids=[...new Set(holdings.map(h=>coinIds[h.symbol]).filter(Boolean))];if(ids.length)prices=await coingecko(`/simple/price?ids=${ids.join(',')}&vs_currencies=eur`)}catch{el('marketStatus').textContent='CoinGecko nicht erreichbar — manuelle Kurse werden verwendet.'}holdings.forEach((h,i)=>{const price=prices[coinIds[h.symbol]]?.eur||h.price||0,value=h.amount*price,gain=value-(h.cost||0);total+=value;cost+=h.cost||0;el('holdings').insertAdjacentHTML('beforeend',`<tr><td>${h.symbol}</td><td>${number.format(h.amount)}</td><td>${money(price)}</td><td>${money(value)}<br><small style="color:${gain>=0?'#285c31':'#8a3535'}">${gain>=0?'+':''}${money(gain)}</small></td><td><button class="btn small ghost" data-remove="${i}">×</button></td></tr>`)});el('portfolioTotal').textContent=money(total);el('marketStatus').textContent+=` · Kostenbasis ${money(cost)} · unrealisiert ${money(total-cost)}`;el('holdings').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{holdings.splice(+b.dataset.remove,1);save();render()})};
  button.onclick=()=>{holdings.push({symbol:el('symbol').value,amount:+el('amount').value,price:+el('manualPrice').value,cost:+el('holdingCost').value,date:el('holdingDate').value});save();render()};
  el('exportHoldings').insertAdjacentHTML('afterend','<label class="btn small ghost" style="cursor:pointer">CSV importieren<input id="holdingImport" type="file" accept=".csv" hidden></label>');
  el('exportHoldings').onclick=()=>csvDownload('portfolio.csv',[['Coin','Menge','Manueller Kurs','Kostenbasis','Kaufdatum'],...holdings.map(h=>[h.symbol,h.amount,h.price,h.cost,h.date])]);
  el('holdingImport').onchange=async event=>{const rows=parseCSV(await event.target.files[0].text());holdings=rows.filter(r=>r[0]).map(r=>({symbol:r[0].toUpperCase(),amount:+r[1],price:+r[2],cost:+r[3],date:r[4]}));save();render()};render();
}

function initCoin(){
  const panel=el('coinResult');panel.insertAdjacentHTML('afterend','<div class="tool-panel" style="margin-top:18px"><h3 class="subhead">Manuelle Due Diligence</h3><p class="tool-note">Markiere nur Punkte, die du anhand unabhängiger Quellen selbst belegt hast.</p><label><input type="checkbox" class="dd"> Team und relevante Erfahrung verifizierbar</label><label><input type="checkbox" class="dd"> Produkt hat nachvollziehbare unabhängige Nutzer</label><label><input type="checkbox" class="dd"> Token-Verteilung und Unlock-Plan verständlich</label><label><input type="checkbox" class="dd"> Admin-Rechte und Smart-Contract-Audit geprüft</label><label><input type="checkbox" class="dd"> Liquidität und größte Holder geprüft</label><label><input type="checkbox" class="dd"> Einnahmen/Anreize des Projekts nachvollziehbar</label><div class="metric" style="margin-top:16px"><span>Manuell belegt</span><strong id="ddScore">0 / 6</strong></div></div>');
  document.querySelectorAll('.dd').forEach(box=>box.onchange=()=>el('ddScore').textContent=`${[...document.querySelectorAll('.dd')].filter(x=>x.checked).length} / 6`);
  el('analyze').onclick=async()=>{const slug=el('coinId').value.trim().toLowerCase();panel.innerHTML='<p>Daten werden geladen …</p>';try{const c=await coingecko(`/coins/${encodeURIComponent(slug)}?localization=false&tickers=false&community_data=true&developer_data=true&sparkline=false`),m=c.market_data||{},d=c.developer_data||{},q=c.community_data||{};const liquidity=clamp((m.total_volume?.eur||0)/(m.market_cap?.eur||1)*250,0,25),developer=clamp((d.commit_count_4_weeks||0)/4,0,25),community=clamp(Math.log10((q.twitter_followers||0)+10)*4,0,25),age=clamp((new Date().getFullYear()-new Date(c.genesis_date||Date.now()).getFullYear())*3,0,25),score=Math.round(liquidity+developer+community+age);panel.innerHTML=`<div class="result-hero"><span class="updated">CoinGecko-Daten</span><div class="result-value">${c.name}: ${score}/100</div><p>Automatisches Research-Signal — keine Qualitäts- oder Kaufbewertung.</p></div>${[['Handelsliquidität',liquidity],['Entwickleraktivität',developer],['Community-Größe',community],['Projekthistorie',age]].map(([label,value])=>`<div class="score-row"><span>${label}</span><strong>${Math.round(value)}/25</strong></div>`).join('')}<div class="metrics" style="margin-top:14px"><div class="metric"><span>Marktkapitalisierung</span><strong>${money(m.market_cap?.eur)}</strong></div><div class="metric"><span>24h Volumen</span><strong>${money(m.total_volume?.eur)}</strong></div></div><div class="warning-box"><strong>Score-Grenze:</strong> Ein Projekt kann Daten, Aktivität oder Community manipulieren. Nutze zusätzlich die manuelle Prüfung.</div>`}catch(error){panel.innerHTML=`<div class="warning-box">Coin nicht gefunden oder Datenquelle nicht erreichbar: ${error.message}</div>`}};
}

function fifoReport(transactions){
  const lots={},results=[];let taxable=0,exempt=0;
  [...transactions].sort((a,b)=>new Date(a.date)-new Date(b.date)).forEach(tx=>{const coin=tx.coin.toUpperCase();lots[coin]??=[];if(['buy','staking','airdrop'].includes(tx.type)){lots[coin].push({date:tx.date,remaining:+tx.amount,cost:+tx.total+(+tx.fee||0),unit:(+tx.total+(+tx.fee||0))/(+tx.amount||1),source:tx.type});return}if(tx.type==='sell'){let remaining=+tx.amount,proceeds=+tx.total-(+tx.fee||0),matchedCost=0,exemptGain=0,taxableGain=0;for(const lot of lots[coin]){if(remaining<=1e-12)break;const used=Math.min(remaining,lot.remaining),cost=used*lot.unit,share=used/(+tx.amount||1),gain=proceeds*share-cost,days=Math.floor((new Date(tx.date)-new Date(lot.date))/86400000);lot.remaining-=used;remaining-=used;matchedCost+=cost;if(days>=365){exemptGain+=gain;exempt+=gain}else{taxableGain+=gain;taxable+=gain}}results.push({...tx,matched:+tx.amount-remaining,unmatched:remaining,cost:matchedCost,taxableGain,exemptGain})}});return{lots,results,taxable,exempt};
}
function initTax(){
  const type=el('txType');type.innerHTML='<option value="buy">Kauf</option><option value="sell">Verkauf</option><option value="staking">Staking-Ertrag</option><option value="airdrop">Airdrop</option>';
  el('txDays').closest('label')?.remove();el('txDays')?.remove();el('txCost').closest('label')?.remove();el('txCost')?.remove();
  el('txTotal').insertAdjacentHTML('afterend','<label>Gebühr in EUR</label><input id="txFee" type="number" value="0" step="any">');
  let transactions=JSON.parse(storage.get('gs-tax-v2'));
  const save=()=>storage.set('gs-tax-v2',JSON.stringify(transactions));
  const render=()=>{const report=fifoReport(transactions);el('transactions').innerHTML='';transactions.forEach((tx,i)=>el('transactions').insertAdjacentHTML('beforeend',`<tr><td>${tx.date}</td><td>${({buy:'Kauf',sell:'Verkauf',staking:'Staking',airdrop:'Airdrop'})[tx.type]}</td><td>${tx.coin}</td><td>${number.format(tx.amount)}</td><td>${money(tx.total)}</td><td>${tx.type==='sell'?'<span class="status">FIFO</span>':'<span class="status good">Los</span>'}</td><td><button class="btn small ghost" data-remove="${i}">×</button></td></tr>`));el('taxableGain').textContent=money(report.taxable);el('threshold').textContent=`FIFO-erfasst · steuerfrei nach Haltedauer: ${money(report.exempt)}`;el('transactions').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{transactions.splice(+b.dataset.remove,1);save();render()});const unmatched=report.results.reduce((s,r)=>s+r.unmatched,0);if(unmatched>0)el('threshold').textContent+=` · WARNUNG: ${number.format(unmatched)} Einheiten ohne Kauf-Los`};
  el('addTx').onclick=()=>{transactions.push({date:el('txDate').value,type:type.value,coin:el('txCoin').value.toUpperCase(),amount:+el('txAmount').value,total:+el('txTotal').value,fee:+el('txFee').value||0});save();render()};
  el('exportTax').insertAdjacentHTML('afterend','<label class="btn small ghost">CSV importieren<input id="taxImport" type="file" accept=".csv" hidden></label>');
  el('exportTax').onclick=()=>csvDownload('krypto-fifo.csv',[['Datum','Typ','Coin','Menge','Wert EUR','Gebühr EUR'],...transactions.map(t=>[t.date,t.type,t.coin,t.amount,t.total,t.fee])]);
  el('taxImport').onchange=async event=>{const rows=parseCSV(await event.target.files[0].text());transactions=rows.filter(r=>r[0]).map(r=>({date:r[0],type:r[1],coin:r[2].toUpperCase(),amount:+r[3],total:+r[4],fee:+r[5]||0}));save();render()};render();
}

try{({savings:initSavings,retirement:initRetirement,portfolio:initPortfolio,coin:initCoin,tax:initTax}[document.body.dataset.tool]||(()=>{}))()}catch(error){console.error(error);document.querySelector('.result-panel')?.insertAdjacentHTML('afterbegin',`<div class="warning-box"><strong>Initialisierungsfehler:</strong> ${error.message}</div>`)}
